sudo: required
dist: trusty
addons:
    apt:
        update: true
        packages:
            - python-clang-3.8
            - libclang-3.8-dev
jobs:
  include:
    - name: "Python Tests"
      language: python
      python:
        - 2.7
      install:
        - pip install -r requirements.txt
      virtualenv:
         system_site_packages: true
      script:
        - python -m unittest discover tests
